package com.bzsoft.oworld.assets.tools;

public enum PlayerState {

	ATTACKN, ATTACKNE, ATTACKE, ATTACKSE, ATTACKS, ATTACKSW, ATTACKW, ATTACKNW,

	BEENHITN, BEENHITNE, BEENHITE, BEENHITSE, BEENHITS, BEENHITSW, BEENHITW, BEENHITNW,

	LOOKINGN, LOOKINGNE, LOOKINGE, LOOKINGSE, LOOKINGS, LOOKINGSW, LOOKINGW, LOOKINGNW,

	PAUSEDN, PAUSEDNE, PAUSEDE, PAUSEDSE, PAUSEDS, PAUSEDSW, PAUSEDW, PAUSEDNW,

	ROARINGN, ROARINGNE, ROARINGE, ROARINGSE, ROARINGS, ROARINGSW, ROARINGW, ROARINGNW,

	RUNNINGN, RUNNINGNE, RUNNINGE, RUNNINGSE, RUNNINGS, RUNNINGSW, RUNNINGW, RUNNINGNW,

	STOPPEDN, STOPPEDNE, STOPPEDE, STOPPEDSE, STOPPEDS, STOPPEDSW, STOPPEDW, STOPPEDNW,

	TIPPINGOVERN, TIPPINGOVERNE, TIPPINGOVERE, TIPPINGOVERSE, TIPPINGOVERS, TIPPINGOVERSW, TIPPINGOVERW, TIPPINGOVERNW,

	WALKINGN, WALKINGNE, WALKINGE, WALKINGSE, WALKINGS, WALKINGSW, WALKINGW, WALKINGNW,

	TALKINGN, TALKINGNE, TALKINGE, TALKINGSE, TALKINGS, TALKINGSW, TALKINGW, TALKINGNW
}
